### ISSUE TITLE
Is nine dead ?

### ISSUE THREAD

**Issue by waghanza** [nandoflorestan/nine#2]
Hi,

As discussed here => https://github.com/slackapi/python-slackclient/pull/240, `nine` seems to be inactive (in face of `six`).

Is is still a good idea to switch from `six` to `nine`, for a **python3** library ?

Regards,

**Comment by nandoflorestan** [comment]
I will comment here in case someone else has the same question.

As discussed in the link above, nine is not dead, it just seems to already be everything you need. Migration to Python 3 is an old problem by now.

I recommend *nine* over *six* because, if you are going through the trouble of upgrading your code to be compatible with Python 3, then this is the best time to drop Python 2 mannerisms.

Both six and nine are very very very small libraries (one Python module). nine is a better tool for the job of migration to Python 3, but you might only realize this later, when you have used six but you still keep seeing those Python 2 idioms in your code.

nine is packaged in Debian, Ubuntu, Fedora and perhaps other distros too.
